sudo: false

git:
  depth: 10

branches:
  only:
    - master
    - next

language: node_js

cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  fast_finish: true
  include:
    - node_js: "12"
      script: npm run $JOB_PART
      env: JOB_PART=pretest
    - node_js: "12"
      script: npm run $JOB_PART
      env: JOB_PART=test:only
    - node_js: "10"
      script: npm run $JOB_PART
      env: JOB_PART=test:only
    - node_js: "8"
      script: npm run $JOB_PART
      env: JOB_PART=test:only

before_install:
  - npm install -g npm@latest

install:
  - npm ci

before_script:
  - node --version
  - npm --version

script:
  - npm run $JOB_PART
