sudo: false
language: node_js
node_js:
    - '6'
    - '5'
# https://github.com/eslint/eslint/issues/3458
#    - '4'
cache:
    directories:
    - node_modules
before_install:
    - npm prune
    - npm update
