sudo: false

git:
  depth: 10

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  fast_finish: true
  include:
    - node_js: '10'
      script: npm run $JOB_PART
      env: JOB_PART=pretest
    - node_js: '10'
      script: npm run $JOB_PART
      env: JOB_PART=test-only
    - node_js: '8'
      script: npm run $JOB_PART
      env: JOB_PART=test-only
    - node_js: '6'
      script: npm run $JOB_PART
      env: JOB_PART=test-only

before_install:
  - 'if [[ `npm -v` != 6* ]]; then npm i -g npm@latest; fi'
  - nvm --version
  - node --version
  - npm --version
